"Domain.Address" = "Address"
"Domain.BirthDate" = "Birth date"
"Domain.CellPhone" = "CellPhone"
"Domain.Classification" = "Number of members"
"Domain.Date" = "Date"
"Domain.Email" = "Email"
"Domain.MarriageDate" = "Marriage Date"
"Domain.MembersQuantity" = "Number of members"
"Domain.Name" = "Name"
"Domain.Phone" = "Phone"
"Reports.Title.Default" = "Member's report"
"Reports.Title.Legal" = "Member's report - Legal"
