coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 0%
ignore:
  - "/entity/bson.go"
  - "/member/repository"
  - "/utils/utilsMongoRepository.go"
  - "/infra"
  - "/reports/reportsRepository.go"
  - "main.go"