mongo:
  url: "mongodb://127.0.0.1:27017/admin"
auth:
  enable: false
church:
  name: "Igreja Evangélica de Pinheiros na Vila São Francisco"
bundle:
  location: "/home/runner/work/church-members-api/church-members-api/bundles"