"Domain.Address" = "Endereço"
"Domain.BirthDate" = "Dt. Nascimento"
"Domain.CellPhone" = "Telefone"
"Domain.Classification" = "Classificação"
"Domain.Date" = "Data"
"Domain.Email" = "Email"
"Domain.MarriageDate" = "Dt. Casamento"
"Domain.MembersQuantity" = "Quantidade de Membros"
"Domain.Name" = "Nome"
"Domain.Phone" = "Telefone"
"Reports.Title.Default" = "Relatório de Membros"
"Reports.Title.Legal" = "Relatório de Membros - Jurídico"
