name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: brunodm2943
          password: ${{ secrets.DOCKER_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: brunodm2943/church-members-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
