name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - name: Create Configuration folder
      run: mkdir -p /home/runner/work/church-members-api/church-members-api/handler/config
      
    - name: Set up configurations files
      run: cp ./config/* /home/runner/work/church-members-api/church-members-api/handler/config

    - name: Create location folder
      run: mkdir -p /src/github.com/BrunoDM2943/church-members-api/bundles
      
    - name: Set up location files
      run: cp ./bundles/* /src/github.com/BrunoDM2943/church-members-api/bundles

    - name: Test
      run: go test -v ./...
